### ISSUE TITLE
Can't compile, difficult to find actual error

### ISSUE THREAD

**Issue by madsl** [flohoff/amifldrv#1]
Tested this on a new system, can't get it to compile...

```
# make
make -C /lib/modules/5.14.9-gentoo/build SUBDIRS=/root/afulnx/amifldrv modules
make[1]: Entering directory '/usr/src/linux-5.14.9-gentoo'
  CALL    scripts/checksyscalls.sh
  CALL    scripts/atomic/check-atomics.sh
  DESCEND objtool
make[1]: Leaving directory '/usr/src/linux-5.14.9-gentoo'
rm -f amifldrv.o_shipped
mv amifldrv.o amifldrv.o_shipped
mv: cannot stat 'amifldrv.o': No such file or directory
make: *** [Makefile:10: default] Error 1
```
You have any tips for what it could be?

**Comment by madsl** [comment]
[stracemake.log](https://github.com/flohoff/amifldrv/files/7310433/stracemake.log)

**Comment by madsl** [comment]
Tested with gcc 6.5.0 and 11.2.0. Log is from 11.2.0.

**Comment by madsl** [comment]
This fork worked (SUBDIRS= vs M=): https://github.com/rigred/amifldrv

You should pull in those changes...

**Comment by flohoff** [comment]
Hi, i cherry picked the 3 patches but not the binary. I dont think we have any license/right to distribute the binary. This is why i initially had only instruction where to find it.

Flo
